name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create env.txt file
        run: |
          touch env.txt
          echo "PB_URL=https://api.cabukcan.com" >> env.txt
          echo "LIVEKIT_URL=${{ secrets.LIVEKIT_URL }}" >> env.txt
          echo "LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}" >> env.txt
          echo "LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}" >> env.txt

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
